"""Classic-control scenarios rendered with the generic primitive renderer."""
from __future__ import annotations

from ..envs import cartpole, drone, lander, mountain_car, pendulum
from .spec import ScenarioSpec

CLASSIC_SPECS: list[ScenarioSpec] = [
    ScenarioSpec(
        id="lunar-lander", name="Lunar Lander", group="Classic",
        kind="generic",
        description="Main + side thrusters, limited fuel. Touch down softly on the pad.",
        metric_label="landing error", metric_mode="min",
        make_env=lambda jitter: lander.LanderEnv(jitter=jitter),
        scene=lander.scene,
        training_factory=lambda: lander.LanderEnv(
            jitter=True, approach_curriculum=True),
        training_start_distribution=lander.TRAINING_START_DISTRIBUTION,
        objective="Reach the landing pad with low velocity, low tilt, and minimal fuel use.",
        success="Touch the pad below all horizontal, vertical, and tilt limits.",
        observations=("pad-relative position", "linear velocity", "tilt and angular rate", "fuel"),
        observation_dimensions=("horizontal pad offset / 300", "vertical pad offset / 300",
                                "horizontal velocity / 60", "vertical velocity / 60",
                                "sin tilt", "cos tilt", "angular rate / 3", "fuel fraction",
                                "remaining horizon fraction"),
        actions=("main-engine throttle", "signed side-thruster command"),
        reward_terms=("decrease distance, speed, and absolute tilt",
                      "−0.03 × main-engine throttle", "+100 soft landing / −100 crash"),
        termination_conditions=("terrain contact", "leaving the arena", "24-second horizon"),
        difficulty="Advanced", horizon_steps=lander.LanderEnv.max_steps,
        horizon_seconds=lander.LanderEnv.max_steps * lander.LanderEnv.dt,
        checkpoint_schema=3),
    ScenarioSpec(
        id="pendulum-swingup", name="Pendulum Swing-Up", group="Classic",
        kind="generic",
        description="One torque motor. Swing the pendulum up and hold it there.",
        metric_label="balance", metric_mode="max",
        make_env=lambda jitter: pendulum.PendulumEnv(jitter=jitter),
        scene=pendulum.scene,
        objective="Minimize angle, angular speed, and control effort around upright.",
        success="Hold near upright through the final quarter of the episode.",
        observations=("cosine and sine of angle", "angular velocity"),
        observation_dimensions=("cos angle", "sin angle", "angular velocity / 8",
                                "remaining horizon fraction"),
        actions=("signed motor torque",),
        reward_terms=("−angle²", "−0.1 × angular-speed²", "−0.001 × torque²"),
        termination_conditions=("fixed 16-second horizon",),
        difficulty="Intermediate", horizon_steps=pendulum.PendulumEnv.max_steps,
        horizon_seconds=pendulum.PendulumEnv.max_steps * pendulum.PendulumEnv.dt,
        checkpoint_schema=2),
    ScenarioSpec(
        id="drone-hover", name="Drone Course", group="Classic",
        kind="generic",
        description="Two rotors, five waypoints. Fly the course without tipping over.",
        metric_label="waypoints", metric_mode="max",
        make_env=lambda jitter: drone.DroneEnv(jitter=jitter),
        scene=drone.scene,
        training_factory=lambda: drone.DroneEnv(
            jitter=True, waypoint_start_curriculum=True),
        training_start_distribution=drone.TRAINING_START_DISTRIBUTION,
        objective="Capture all waypoints while controlling attitude and energy use.",
        success="Capture all five waypoints without tipping or leaving the arena.",
        observations=("target-relative position", "linear velocity", "tilt and angular rate", "course progress"),
        observation_dimensions=("target horizontal offset / 300", "target vertical offset / 300",
                                "horizontal velocity / 60", "vertical velocity / 60",
                                "sin tilt", "cos tilt", "angular rate / 4", "waypoint fraction",
                                "remaining horizon fraction"),
        actions=("left-rotor thrust", "right-rotor thrust"),
        reward_terms=("+0.05 × decrease in waypoint distance", "+20 per waypoint and +50 course completion",
                      "angular-rate and squared-thrust costs", "−50 crash"),
        termination_conditions=("all waypoints captured", "tip or arena exit", "36-second horizon"),
        difficulty="Advanced", horizon_steps=drone.DroneEnv.max_steps,
        horizon_seconds=drone.DroneEnv.max_steps * drone.DroneEnv.dt,
        checkpoint_schema=4),
    ScenarioSpec(
        id="cartpole-balance", name="Continuous Cart-Pole", group="Foundations",
        kind="generic",
        description="A disclosed continuous-force, semi-implicit CartPole variant; not Gymnasium CartPole-v1.",
        metric_label="balance time", metric_mode="max",
        make_env=lambda jitter: cartpole.CartPoleEnv(jitter=jitter),
        scene=cartpole.scene,
        objective="Maximize the time the pole remains upright and the cart remains in bounds.",
        success="Balance for the full 10-second horizon.",
        observations=("cart position", "cart velocity", "pole angle", "pole angular velocity"),
        observation_dimensions=("cart position / 2.4", "cart velocity / 3",
                                "pole angle / 12°", "pole angular velocity / 3.5",
                                "remaining horizon fraction"),
        actions=("signed horizontal force",),
        reward_terms=("+1 for every safe control step", "0 on the failure transition"),
        termination_conditions=("cart leaves ±2.4 m", "pole exceeds ±12°", "500-step horizon"),
        difficulty="Introductory", horizon_steps=cartpole.CartPoleEnv.max_steps,
        horizon_seconds=cartpole.CartPoleEnv.max_steps * cartpole.CartPoleEnv.dt,
        checkpoint_schema=2),
    ScenarioSpec(
        id="mountain-car", name="Mountain Car", group="Foundations",
        kind="generic",
        description="Build momentum across a valley to reach a goal the motor cannot climb directly.",
        metric_label="control effort", metric_mode="min",
        make_env=lambda jitter: mountain_car.MountainCarEnv(jitter=jitter),
        scene=mountain_car.scene,
        objective="Reach the summit while minimizing squared control effort.",
        success="Cross the goal flag before the 999-step horizon.",
        observations=("normalized position", "normalized velocity"),
        observation_dimensions=("position mapped to [−1, +1]", "velocity / 0.07",
                                "remaining horizon fraction"),
        actions=("signed motor force",),
        reward_terms=("+100 on reaching the summit", "−0.1 × squared motor command per step"),
        termination_conditions=("position reaches 0.45", "999-control-step horizon"),
        difficulty="Introductory", horizon_steps=mountain_car.MountainCarEnv.max_steps,
        horizon_seconds=None,
        checkpoint_schema=3),
]
